// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package sqlc

import (
	"context"
)

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM vault_apps WHERE uuid = ?
`

func (q *Queries) DeleteApp(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteApp, uuid)
	return err
}

const getAppByName = `-- name: GetAppByName :one
SELECT id, uuid, name, description, service_id, db_path, status, secret_count, created_at, last_accessed_at FROM vault_apps WHERE name = ? LIMIT 1
`

func (q *Queries) GetAppByName(ctx context.Context, name string) (VaultApp, error) {
	row := q.db.QueryRowContext(ctx, getAppByName, name)
	var i VaultApp
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.DbPath,
		&i.Status,
		&i.SecretCount,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getAppByUUID = `-- name: GetAppByUUID :one
SELECT id, uuid, name, description, service_id, db_path, status, secret_count, created_at, last_accessed_at FROM vault_apps WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetAppByUUID(ctx context.Context, uuid string) (VaultApp, error) {
	row := q.db.QueryRowContext(ctx, getAppByUUID, uuid)
	var i VaultApp
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.DbPath,
		&i.Status,
		&i.SecretCount,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const listActiveApps = `-- name: ListActiveApps :many
SELECT id, uuid, name, description, service_id, db_path, status, secret_count, created_at, last_accessed_at FROM vault_apps WHERE status = 'active' ORDER BY name
`

func (q *Queries) ListActiveApps(ctx context.Context) ([]VaultApp, error) {
	rows, err := q.db.QueryContext(ctx, listActiveApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultApp{}
	for rows.Next() {
		var i VaultApp
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.ServiceID,
			&i.DbPath,
			&i.Status,
			&i.SecretCount,
			&i.CreatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApps = `-- name: ListApps :many
SELECT id, uuid, name, description, service_id, db_path, status, secret_count, created_at, last_accessed_at FROM vault_apps ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context) ([]VaultApp, error) {
	rows, err := q.db.QueryContext(ctx, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultApp{}
	for rows.Next() {
		var i VaultApp
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.ServiceID,
			&i.DbPath,
			&i.Status,
			&i.SecretCount,
			&i.CreatedAt,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerApp = `-- name: RegisterApp :exec
INSERT INTO vault_apps (uuid, name, description, service_id, db_path, status)
VALUES (?, ?, ?, ?, ?, 'active')
`

type RegisterAppParams struct {
	Uuid        string  `json:"uuid"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ServiceID   *string `json:"service_id"`
	DbPath      string  `json:"db_path"`
}

func (q *Queries) RegisterApp(ctx context.Context, arg RegisterAppParams) error {
	_, err := q.db.ExecContext(ctx, registerApp,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.ServiceID,
		arg.DbPath,
	)
	return err
}

const updateAppLastAccessed = `-- name: UpdateAppLastAccessed :exec
UPDATE vault_apps SET last_accessed_at = CURRENT_TIMESTAMP WHERE uuid = ?
`

func (q *Queries) UpdateAppLastAccessed(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, updateAppLastAccessed, uuid)
	return err
}

const updateAppSecretCount = `-- name: UpdateAppSecretCount :exec
UPDATE vault_apps SET secret_count = ? WHERE uuid = ?
`

type UpdateAppSecretCountParams struct {
	SecretCount *int64 `json:"secret_count"`
	Uuid        string `json:"uuid"`
}

func (q *Queries) UpdateAppSecretCount(ctx context.Context, arg UpdateAppSecretCountParams) error {
	_, err := q.db.ExecContext(ctx, updateAppSecretCount, arg.SecretCount, arg.Uuid)
	return err
}

const updateAppStatus = `-- name: UpdateAppStatus :exec
UPDATE vault_apps SET status = ? WHERE uuid = ?
`

type UpdateAppStatusParams struct {
	Status string `json:"status"`
	Uuid   string `json:"uuid"`
}

func (q *Queries) UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAppStatus, arg.Status, arg.Uuid)
	return err
}
