// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"time"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM vault_audit_log
`

func (q *Queries) CountAuditLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO vault_audit_log (action, profile_name, secret_key, detail)
VALUES (?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	Action      string  `json:"action"`
	ProfileName string  `json:"profile_name"`
	SecretKey   *string `json:"secret_key"`
	Detail      *string `json:"detail"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.Action,
		arg.ProfileName,
		arg.SecretKey,
		arg.Detail,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, "action", profile_name, secret_key, detail, created_at FROM vault_audit_log ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListAuditLog(ctx context.Context, limit int64) ([]VaultAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAuditLog{}
	for rows.Next() {
		var i VaultAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ProfileName,
			&i.SecretKey,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByAction = `-- name: ListAuditLogByAction :many
SELECT id, "action", profile_name, secret_key, detail, created_at FROM vault_audit_log WHERE action = ? ORDER BY created_at DESC LIMIT ?
`

type ListAuditLogByActionParams struct {
	Action string `json:"action"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAuditLogByAction(ctx context.Context, arg ListAuditLogByActionParams) ([]VaultAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByAction, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAuditLog{}
	for rows.Next() {
		var i VaultAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ProfileName,
			&i.SecretKey,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByProfile = `-- name: ListAuditLogByProfile :many
SELECT id, "action", profile_name, secret_key, detail, created_at FROM vault_audit_log WHERE profile_name = ? ORDER BY created_at DESC LIMIT ?
`

type ListAuditLogByProfileParams struct {
	ProfileName string `json:"profile_name"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListAuditLogByProfile(ctx context.Context, arg ListAuditLogByProfileParams) ([]VaultAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByProfile, arg.ProfileName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultAuditLog{}
	for rows.Next() {
		var i VaultAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ProfileName,
			&i.SecretKey,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditLog = `-- name: PurgeAuditLog :exec
DELETE FROM vault_audit_log WHERE created_at < ?
`

func (q *Queries) PurgeAuditLog(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, purgeAuditLog, createdAt)
	return err
}
