// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keys.sql

package sqlc

import (
	"context"
)

const deleteKey = `-- name: DeleteKey :exec
DELETE
FROM vault_keys
WHERE name = ? AND algorithm = ?
`

type DeleteKeyParams struct {
	Name      string `json:"name"`
	Algorithm string `json:"algorithm"`
}

func (q *Queries) DeleteKey(ctx context.Context, arg DeleteKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteKey, arg.Name, arg.Algorithm)
	return err
}

const deleteKeyByName = `-- name: DeleteKeyByName :exec
DELETE
FROM vault_keys
WHERE name = ?
`

func (q *Queries) DeleteKeyByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteKeyByName, name)
	return err
}

const getKey = `-- name: GetKey :one
SELECT id, name, algorithm, encrypted_private_key, nonce, public_key, fingerprint, description, created_at
FROM vault_keys
WHERE name = ? AND algorithm = ? LIMIT 1
`

type GetKeyParams struct {
	Name      string `json:"name"`
	Algorithm string `json:"algorithm"`
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (VaultKey, error) {
	row := q.db.QueryRowContext(ctx, getKey, arg.Name, arg.Algorithm)
	var i VaultKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.EncryptedPrivateKey,
		&i.Nonce,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getKeyByName = `-- name: GetKeyByName :one
SELECT id, name, algorithm, encrypted_private_key, nonce, public_key, fingerprint, description, created_at
FROM vault_keys
WHERE name = ? LIMIT 1
`

func (q *Queries) GetKeyByName(ctx context.Context, name string) (VaultKey, error) {
	row := q.db.QueryRowContext(ctx, getKeyByName, name)
	var i VaultKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.EncryptedPrivateKey,
		&i.Nonce,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertKey = `-- name: InsertKey :exec
INSERT INTO vault_keys (name, algorithm, encrypted_private_key, nonce, public_key, fingerprint, description)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertKeyParams struct {
	Name                string  `json:"name"`
	Algorithm           string  `json:"algorithm"`
	EncryptedPrivateKey []byte  `json:"encrypted_private_key"`
	Nonce               []byte  `json:"nonce"`
	PublicKey           []byte  `json:"public_key"`
	Fingerprint         string  `json:"fingerprint"`
	Description         *string `json:"description"`
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertKey,
		arg.Name,
		arg.Algorithm,
		arg.EncryptedPrivateKey,
		arg.Nonce,
		arg.PublicKey,
		arg.Fingerprint,
		arg.Description,
	)
	return err
}

const keyExists = `-- name: KeyExists :one
SELECT COUNT(*)
FROM vault_keys
WHERE name = ? AND algorithm = ?
`

type KeyExistsParams struct {
	Name      string `json:"name"`
	Algorithm string `json:"algorithm"`
}

func (q *Queries) KeyExists(ctx context.Context, arg KeyExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, keyExists, arg.Name, arg.Algorithm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const keyExistsByName = `-- name: KeyExistsByName :one
SELECT COUNT(*)
FROM vault_keys
WHERE name = ?
`

func (q *Queries) KeyExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, keyExistsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllKeys = `-- name: ListAllKeys :many
SELECT id, name, algorithm, encrypted_private_key, nonce, public_key, fingerprint, description, created_at
FROM vault_keys
ORDER BY name, algorithm
`

func (q *Queries) ListAllKeys(ctx context.Context) ([]VaultKey, error) {
	rows, err := q.db.QueryContext(ctx, listAllKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultKey{}
	for rows.Next() {
		var i VaultKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Algorithm,
			&i.EncryptedPrivateKey,
			&i.Nonce,
			&i.PublicKey,
			&i.Fingerprint,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT id, name, algorithm, encrypted_private_key, nonce, public_key, fingerprint, description, created_at
FROM vault_keys
ORDER BY name, algorithm
`

func (q *Queries) ListKeys(ctx context.Context) ([]VaultKey, error) {
	rows, err := q.db.QueryContext(ctx, listKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultKey{}
	for rows.Next() {
		var i VaultKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Algorithm,
			&i.EncryptedPrivateKey,
			&i.Nonce,
			&i.PublicKey,
			&i.Fingerprint,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
