// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type VaultAuditLog struct {
	ID          int64     `json:"id"`
	Action      string    `json:"action"`
	ProfileName string    `json:"profile_name"`
	SecretKey   *string   `json:"secret_key"`
	Detail      *string   `json:"detail"`
	CreatedAt   time.Time `json:"created_at"`
}

type VaultPassword struct {
	ID           int64      `json:"id"`
	PasswordHash []byte     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type VaultProfile struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	IsDefault   *int64     `json:"is_default"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type VaultSealedKey struct {
	ID            int64      `json:"id"`
	SealedData    []byte     `json:"sealed_data"`
	Nonce         []byte     `json:"nonce"`
	KeySalt       []byte     `json:"key_salt"`
	Version       *int64     `json:"version"`
	MachineIDHash []byte     `json:"machine_id_hash"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
	SealMethod    string     `json:"seal_method"`
}

type VaultSecret struct {
	ID             int64      `json:"id"`
	ProfileName    string     `json:"profile_name"`
	Key            string     `json:"key"`
	EncryptedValue []byte     `json:"encrypted_value"`
	Nonce          []byte     `json:"nonce"`
	Description    *string    `json:"description"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

type VaultSecretVersion struct {
	ID             int64     `json:"id"`
	ProfileName    string    `json:"profile_name"`
	Key            string    `json:"key"`
	Version        int64     `json:"version"`
	EncryptedValue []byte    `json:"encrypted_value"`
	Nonce          []byte    `json:"nonce"`
	CreatedAt      time.Time `json:"created_at"`
}

type VaultTemplate struct {
	ID           int64      `json:"id"`
	Name         string     `json:"name"`
	Description  *string    `json:"description"`
	TemplateData string     `json:"template_data"`
	Builtin      *int64     `json:"builtin"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
