// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password.sql

package sqlc

import (
	"context"
)

const deletePassword = `-- name: DeletePassword :exec
DELETE
FROM vault_password
WHERE id = 1
`

func (q *Queries) DeletePassword(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePassword)
	return err
}

const getPassword = `-- name: GetPassword :one
SELECT id, password_hash, created_at, updated_at
FROM vault_password
WHERE id = 1
`

func (q *Queries) GetPassword(ctx context.Context) (VaultPassword, error) {
	row := q.db.QueryRowContext(ctx, getPassword)
	var i VaultPassword
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPassword = `-- name: HasPassword :one
SELECT COUNT(*)
FROM vault_password
WHERE id = 1
`

func (q *Queries) HasPassword(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasPassword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertPassword = `-- name: UpsertPassword :exec
INSERT INTO vault_password (id, password_hash, created_at, updated_at)
VALUES (1, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT(id) DO
UPDATE SET
    password_hash = excluded.password_hash,
    updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) UpsertPassword(ctx context.Context, passwordHash []byte) error {
	_, err := q.db.ExecContext(ctx, upsertPassword, passwordHash)
	return err
}
