// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"
)

const clearAllDefaultProfiles = `-- name: ClearAllDefaultProfiles :exec
UPDATE vault_profiles SET is_default = 0
`

func (q *Queries) ClearAllDefaultProfiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllDefaultProfiles)
	return err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO vault_profiles (name, description, is_default)
VALUES (?, ?, ?)
`

type CreateProfileParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsDefault   *int64  `json:"is_default"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile, arg.Name, arg.Description, arg.IsDefault)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM vault_profiles WHERE name = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, name)
	return err
}

const getDefaultProfile = `-- name: GetDefaultProfile :one
SELECT id, name, description, is_default, created_at, updated_at FROM vault_profiles WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultProfile(ctx context.Context) (VaultProfile, error) {
	row := q.db.QueryRowContext(ctx, getDefaultProfile)
	var i VaultProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, name, description, is_default, created_at, updated_at FROM vault_profiles WHERE name = ? LIMIT 1
`

func (q *Queries) GetProfileByName(ctx context.Context, name string) (VaultProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByName, name)
	var i VaultProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, description, is_default, created_at, updated_at FROM vault_profiles ORDER BY name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]VaultProfile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultProfile{}
	for rows.Next() {
		var i VaultProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileExists = `-- name: ProfileExists :one
SELECT COUNT(*) FROM vault_profiles WHERE name = ?
`

func (q *Queries) ProfileExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, profileExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setProfileDefault = `-- name: SetProfileDefault :exec
UPDATE vault_profiles SET is_default = 1, updated_at = CURRENT_TIMESTAMP WHERE name = ?
`

func (q *Queries) SetProfileDefault(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, setProfileDefault, name)
	return err
}

const updateProfileDescription = `-- name: UpdateProfileDescription :exec
UPDATE vault_profiles SET description = ?, updated_at = CURRENT_TIMESTAMP WHERE name = ?
`

type UpdateProfileDescriptionParams struct {
	Description *string `json:"description"`
	Name        string  `json:"name"`
}

func (q *Queries) UpdateProfileDescription(ctx context.Context, arg UpdateProfileDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileDescription, arg.Description, arg.Name)
	return err
}
