// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package sqlc

import (
	"context"
)

const deleteRecovery = `-- name: DeleteRecovery :exec
DELETE
FROM vault_recovery
WHERE id = 1
`

func (q *Queries) DeleteRecovery(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRecovery)
	return err
}

const getRecovery = `-- name: GetRecovery :one
SELECT id, mnemonic_hash, enabled, created_at
FROM vault_recovery
WHERE id = 1
`

func (q *Queries) GetRecovery(ctx context.Context) (VaultRecovery, error) {
	row := q.db.QueryRowContext(ctx, getRecovery)
	var i VaultRecovery
	err := row.Scan(
		&i.ID,
		&i.MnemonicHash,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const hasRecovery = `-- name: HasRecovery :one
SELECT COUNT(*)
FROM vault_recovery
WHERE id = 1
`

func (q *Queries) HasRecovery(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasRecovery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertRecovery = `-- name: UpsertRecovery :exec
INSERT INTO vault_recovery (id, mnemonic_hash, enabled, created_at)
VALUES (1, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    mnemonic_hash = excluded.mnemonic_hash,
    enabled = excluded.enabled
`

type UpsertRecoveryParams struct {
	MnemonicHash []byte `json:"mnemonic_hash"`
	Enabled      int64  `json:"enabled"`
}

func (q *Queries) UpsertRecovery(ctx context.Context, arg UpsertRecoveryParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecovery, arg.MnemonicHash, arg.Enabled)
	return err
}
