// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rotation.sql

package sqlc

import (
	"context"
)

const listAllSecrets = `-- name: ListAllSecrets :many
SELECT id, profile_name, "key", encrypted_value, nonce, description, created_at, updated_at FROM vault_secrets ORDER BY profile_name, key
`

func (q *Queries) ListAllSecrets(ctx context.Context) ([]VaultSecret, error) {
	rows, err := q.db.QueryContext(ctx, listAllSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecret{}
	for rows.Next() {
		var i VaultSecret
		if err := rows.Scan(
			&i.ID,
			&i.ProfileName,
			&i.Key,
			&i.EncryptedValue,
			&i.Nonce,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
