// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sealed_key.sql

package sqlc

import (
	"context"
)

const deleteSealedKey = `-- name: DeleteSealedKey :exec
DELETE
FROM vault_sealed_key
WHERE id = 1
`

func (q *Queries) DeleteSealedKey(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSealedKey)
	return err
}

const getSealedKey = `-- name: GetSealedKey :one
SELECT id, sealed_data, nonce, key_salt, version, machine_id_hash, created_at, updated_at, seal_method
FROM vault_sealed_key
WHERE id = 1
`

func (q *Queries) GetSealedKey(ctx context.Context) (VaultSealedKey, error) {
	row := q.db.QueryRowContext(ctx, getSealedKey)
	var i VaultSealedKey
	err := row.Scan(
		&i.ID,
		&i.SealedData,
		&i.Nonce,
		&i.KeySalt,
		&i.Version,
		&i.MachineIDHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SealMethod,
	)
	return i, err
}

const hasSealedKey = `-- name: HasSealedKey :one
SELECT COUNT(*)
FROM vault_sealed_key
WHERE id = 1
`

func (q *Queries) HasSealedKey(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasSealedKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertSealedKey = `-- name: UpsertSealedKey :exec
INSERT INTO vault_sealed_key (id, sealed_data, nonce, key_salt, version, machine_id_hash, seal_method, created_at,
                              updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT(id) DO
UPDATE SET
    sealed_data = excluded.sealed_data,
    nonce = excluded.nonce,
    key_salt = excluded.key_salt,
    version = excluded.version,
    machine_id_hash = excluded.machine_id_hash,
    seal_method = excluded.seal_method,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSealedKeyParams struct {
	SealedData    []byte `json:"sealed_data"`
	Nonce         []byte `json:"nonce"`
	KeySalt       []byte `json:"key_salt"`
	Version       *int64 `json:"version"`
	MachineIDHash []byte `json:"machine_id_hash"`
	SealMethod    string `json:"seal_method"`
}

func (q *Queries) UpsertSealedKey(ctx context.Context, arg UpsertSealedKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertSealedKey,
		arg.SealedData,
		arg.Nonce,
		arg.KeySalt,
		arg.Version,
		arg.MachineIDHash,
		arg.SealMethod,
	)
	return err
}
