// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package sqlc

import (
	"context"
)

const countSecrets = `-- name: CountSecrets :one
SELECT COUNT(*)
FROM vault_secrets
WHERE profile_name = ?
`

func (q *Queries) CountSecrets(ctx context.Context, profileName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecrets, profileName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllSecrets = `-- name: DeleteAllSecrets :exec
DELETE
FROM vault_secrets
WHERE profile_name = ?
`

func (q *Queries) DeleteAllSecrets(ctx context.Context, profileName string) error {
	_, err := q.db.ExecContext(ctx, deleteAllSecrets, profileName)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE
FROM vault_secrets
WHERE profile_name = ? AND key = ?
`

type DeleteSecretParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, arg.ProfileName, arg.Key)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, profile_name, "key", encrypted_value, nonce, description, created_at, updated_at
FROM vault_secrets
WHERE profile_name = ? AND key = ? LIMIT 1
`

type GetSecretParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (VaultSecret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, arg.ProfileName, arg.Key)
	var i VaultSecret
	err := row.Scan(
		&i.ID,
		&i.ProfileName,
		&i.Key,
		&i.EncryptedValue,
		&i.Nonce,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, profile_name, "key", encrypted_value, nonce, description, created_at, updated_at
FROM vault_secrets
WHERE profile_name = ?
ORDER BY key
`

func (q *Queries) ListSecrets(ctx context.Context, profileName string) ([]VaultSecret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets, profileName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecret{}
	for rows.Next() {
		var i VaultSecret
		if err := rows.Scan(
			&i.ID,
			&i.ProfileName,
			&i.Key,
			&i.EncryptedValue,
			&i.Nonce,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretExists = `-- name: SecretExists :one
SELECT COUNT(*)
FROM vault_secrets
WHERE profile_name = ? AND key = ?
`

type SecretExistsParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
}

func (q *Queries) SecretExists(ctx context.Context, arg SecretExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, secretExists, arg.ProfileName, arg.Key)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO vault_secrets (profile_name, key, encrypted_value, nonce, description)
VALUES (?, ?, ?, ?, ?) ON CONFLICT(profile_name, key) DO
UPDATE SET
    encrypted_value = excluded.encrypted_value,
    nonce = excluded.nonce,
    description = excluded.description,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSecretParams struct {
	ProfileName    string  `json:"profile_name"`
	Key            string  `json:"key"`
	EncryptedValue []byte  `json:"encrypted_value"`
	Nonce          []byte  `json:"nonce"`
	Description    *string `json:"description"`
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertSecret,
		arg.ProfileName,
		arg.Key,
		arg.EncryptedValue,
		arg.Nonce,
		arg.Description,
	)
	return err
}
