// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlc

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :exec
INSERT INTO vault_templates (name, description, template_data, builtin)
VALUES (?, ?, ?, ?)
`

type CreateTemplateParams struct {
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	TemplateData string  `json:"template_data"`
	Builtin      *int64  `json:"builtin"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createTemplate,
		arg.Name,
		arg.Description,
		arg.TemplateData,
		arg.Builtin,
	)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM vault_templates WHERE name = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, name)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, description, template_data, builtin, created_at, updated_at FROM vault_templates WHERE name = ? LIMIT 1
`

func (q *Queries) GetTemplate(ctx context.Context, name string) (VaultTemplate, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, name)
	var i VaultTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TemplateData,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, template_data, builtin, created_at, updated_at FROM vault_templates ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context) ([]VaultTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTemplate{}
	for rows.Next() {
		var i VaultTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TemplateData,
			&i.Builtin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const templateExists = `-- name: TemplateExists :one
SELECT COUNT(*) FROM vault_templates WHERE name = ?
`

func (q *Queries) TemplateExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, templateExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE vault_templates SET description = ?, template_data = ?, updated_at = CURRENT_TIMESTAMP WHERE name = ?
`

type UpdateTemplateParams struct {
	Description  *string `json:"description"`
	TemplateData string  `json:"template_data"`
	Name         string  `json:"name"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate, arg.Description, arg.TemplateData, arg.Name)
	return err
}
