// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versions.sql

package sqlc

import (
	"context"
)

const deleteSecretVersions = `-- name: DeleteSecretVersions :exec
DELETE
FROM vault_secret_versions
WHERE profile_name = ? AND key = ?
`

type DeleteSecretVersionsParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteSecretVersions(ctx context.Context, arg DeleteSecretVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecretVersions, arg.ProfileName, arg.Key)
	return err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT CAST(COALESCE(MAX(version), 0) AS INTEGER) AS version
FROM vault_secret_versions
WHERE profile_name = ? AND key = ?
`

type GetLatestVersionNumberParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
}

func (q *Queries) GetLatestVersionNumber(ctx context.Context, arg GetLatestVersionNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionNumber, arg.ProfileName, arg.Key)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getSecretVersion = `-- name: GetSecretVersion :one
SELECT id, profile_name, "key", version, encrypted_value, nonce, created_at
FROM vault_secret_versions
WHERE profile_name = ? AND key = ? AND version = ? LIMIT 1
`

type GetSecretVersionParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
	Version     int64  `json:"version"`
}

func (q *Queries) GetSecretVersion(ctx context.Context, arg GetSecretVersionParams) (VaultSecretVersion, error) {
	row := q.db.QueryRowContext(ctx, getSecretVersion, arg.ProfileName, arg.Key, arg.Version)
	var i VaultSecretVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileName,
		&i.Key,
		&i.Version,
		&i.EncryptedValue,
		&i.Nonce,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecretVersion = `-- name: InsertSecretVersion :exec
INSERT INTO vault_secret_versions (profile_name, key, version, encrypted_value, nonce)
VALUES (?, ?, ?, ?, ?)
`

type InsertSecretVersionParams struct {
	ProfileName    string `json:"profile_name"`
	Key            string `json:"key"`
	Version        int64  `json:"version"`
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
}

func (q *Queries) InsertSecretVersion(ctx context.Context, arg InsertSecretVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertSecretVersion,
		arg.ProfileName,
		arg.Key,
		arg.Version,
		arg.EncryptedValue,
		arg.Nonce,
	)
	return err
}

const listAllSecretVersions = `-- name: ListAllSecretVersions :many
SELECT id, profile_name, "key", version, encrypted_value, nonce, created_at
FROM vault_secret_versions
ORDER BY profile_name, key, version
`

func (q *Queries) ListAllSecretVersions(ctx context.Context) ([]VaultSecretVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAllSecretVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecretVersion{}
	for rows.Next() {
		var i VaultSecretVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProfileName,
			&i.Key,
			&i.Version,
			&i.EncryptedValue,
			&i.Nonce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersions = `-- name: ListSecretVersions :many
SELECT id, profile_name, "key", version, encrypted_value, nonce, created_at
FROM vault_secret_versions
WHERE profile_name = ? AND key = ?
ORDER BY version DESC
`

type ListSecretVersionsParams struct {
	ProfileName string `json:"profile_name"`
	Key         string `json:"key"`
}

func (q *Queries) ListSecretVersions(ctx context.Context, arg ListSecretVersionsParams) ([]VaultSecretVersion, error) {
	rows, err := q.db.QueryContext(ctx, listSecretVersions, arg.ProfileName, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSecretVersion{}
	for rows.Next() {
		var i VaultSecretVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProfileName,
			&i.Key,
			&i.Version,
			&i.EncryptedValue,
			&i.Nonce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecretVersionData = `-- name: UpdateSecretVersionData :exec
UPDATE vault_secret_versions
SET encrypted_value = ?,
    nonce           = ?
WHERE id = ?
`

type UpdateSecretVersionDataParams struct {
	EncryptedValue []byte `json:"encrypted_value"`
	Nonce          []byte `json:"nonce"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateSecretVersionData(ctx context.Context, arg UpdateSecretVersionDataParams) error {
	_, err := q.db.ExecContext(ctx, updateSecretVersionData, arg.EncryptedValue, arg.Nonce, arg.ID)
	return err
}
